services:
  - type: web
    name: snake-game
    env: static
    staticPublishPath: ./
    buildCommand: null
    startCommand: null
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
